webtalk_init -webtalk_dir E:/Development/zose/zose.sim/sim_1/behav/xsim/xsim.dir/zose_synth_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 19 21:47:45 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3e102c77-a6fe-4c98-8b72-eafb19da94d9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0b6985a50b044b7b8a65aa96e020d979" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "162" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3300 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1245480882 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "31.78_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14716_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2617677789 -regid "211359308_1777526039_210659473_505" -xml E:/Development/zose/zose.sim/sim_1/behav/xsim/xsim.dir/zose_synth_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Development/zose/zose.sim/sim_1/behav/xsim/xsim.dir/zose_synth_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Development/zose/zose.sim/sim_1/behav/xsim/xsim.dir/zose_synth_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
