# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/RTL/Arty_constraints.xdc

# Block Designs: bd/zose/zose.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zose || ORIG_REF_NAME==zose} -quiet] -quiet

# IP: bd/zose/ip/zose_square_sampler_0_0/zose_square_sampler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zose_square_sampler_0_0 || ORIG_REF_NAME==zose_square_sampler_0_0} -quiet] -quiet

# IP: bd/zose/ip/zose_clk_wiz_0_0/zose_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zose_clk_wiz_0_0 || ORIG_REF_NAME==zose_clk_wiz_0_0} -quiet] -quiet

# IP: bd/zose/ip/zose_clocker_0_0/zose_clocker_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zose_clocker_0_0 || ORIG_REF_NAME==zose_clocker_0_0} -quiet] -quiet

# IP: bd/zose/ip/zose_driver_output_0_0/zose_driver_output_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zose_driver_output_0_0 || ORIG_REF_NAME==zose_driver_output_0_0} -quiet] -quiet

# IP: bd/zose/ip/zose_switcher_0_0/zose_switcher_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zose_switcher_0_0 || ORIG_REF_NAME==zose_switcher_0_0} -quiet] -quiet

# IP: bd/zose/ip/zose_sinus_sampler_0_0/zose_sinus_sampler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zose_sinus_sampler_0_0 || ORIG_REF_NAME==zose_sinus_sampler_0_0} -quiet] -quiet

# XDC: bd/zose/zose_ooc.xdc
